prepare:
    test_size: 0.33
    random_state: 42
train:
  import_module: sklearn.ensemble
  name: RandomForestClassifier
  params:
    n_estimators: 10
    n_jobs: -1
    random_state: 42
evaluate:
  metrics:
    - accuracy
    - balanced_accuracy
    - adjusted_rand_score
