prepare:
      test_size: 0.33
      random_state: 42
train:
  import_module: sklearn.ensemble
  name: ExtraTreesClassifier
  params:
    n_estimators: 100
    n_jobs: -1
    random_state: 42
evaluate:
  metrics:
    - accuracy
    - balanced_accuracy
    - adjusted_rand_score
